# Generated by Django 5.2.16 on 2026-08-14 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CoreValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide react icon name", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "FAQ Categories",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="journey/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Company Journey / Timeline",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=100)),
                ("tagline", models.TextField(blank=True, null=True)),
                ("best_for", models.TextField(blank=True, null=True)),
                (
                    "project_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("warranty", models.CharField(blank=True, max_length=100, null=True)),
                ("timeline", models.CharField(blank=True, max_length=100, null=True)),
                ("grade", models.CharField(blank=True, max_length=100, null=True)),
                ("plot_size", models.CharField(blank=True, max_length=100, null=True)),
                ("floors", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("ideal_customer", models.TextField(blank=True, null=True)),
                ("limitations", models.TextField(blank=True, null=True)),
                ("upgrades", models.TextField(blank=True, null=True)),
                ("maintenance", models.TextField(blank=True, null=True)),
                ("why_choose", models.TextField(blank=True, null=True)),
                ("construction_quality", models.TextField(blank=True, null=True)),
                (
                    "recommended_budget",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PackageMaterialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Package Material Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("services", "Services"),
                            ("packages", "Packages"),
                            ("projects", "Projects"),
                            ("process", "Process"),
                            ("contact", "Contact"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True, null=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/"),
                ),
                (
                    "hero_video",
                    models.FileField(
                        blank=True,
                        help_text="Upload a background video (e.g. mp4). Overrides hero_image if provided.",
                        null=True,
                        upload_to="pages/videos/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        help_text="e.g. Advance Payment for Material dumping",
                        max_length=255,
                    ),
                ),
                (
                    "percentage_or_condition",
                    models.CharField(
                        help_text="e.g. 10% Based on Total Slab Area", max_length=255
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional additional notes for this milestone",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Term & Condition",
                "verbose_name_plural": "Payment Terms & Conditions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_number",
                    models.CharField(
                        default="01", help_text="e.g. 01, 02, 03", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        default="FileText",
                        help_text="Lucide react icon name",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional custom image for this process step",
                        null=True,
                        upload_to="process/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video URL for this step",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Process Steps / How It Works",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Project Categories",
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Paramarsh Construction", max_length=255),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                (
                    "hero_headline",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Your Dream <br/> Our Build <br/> Complete Site Solutions Under One Roof!",
                        null=True,
                    ),
                ),
                (
                    "hero_subtext",
                    models.TextField(
                        blank=True,
                        help_text="Subheading paragraph under hero title",
                        null=True,
                    ),
                ),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the background video for the homepage hero",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hero_poster_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the poster image while video loads",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hero_primary_btn_text",
                    models.CharField(
                        blank=True,
                        default="Free Consultation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hero_secondary_btn_text",
                    models.CharField(
                        blank=True, default="View Projects", max_length=100, null=True
                    ),
                ),
                (
                    "hero_stat_pill_1",
                    models.CharField(
                        blank=True,
                        default="10+ Live Projects",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "hero_stat_pill_2",
                    models.CharField(
                        blank=True,
                        default="₹1600/sq.ft Starting Price",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "trust_section_image",
                    models.ImageField(
                        blank=True,
                        help_text="Showcase image for Trust & Intro section",
                        null=True,
                        upload_to="site/trust/",
                    ),
                ),
                (
                    "process_section_video_url",
                    models.URLField(
                        blank=True,
                        help_text="Video URL for How It Works process section",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "process_section_poster_image",
                    models.ImageField(
                        blank=True,
                        help_text="Poster image for How It Works process section",
                        null=True,
                        upload_to="site/process/",
                    ),
                ),
                (
                    "about_story_image_1",
                    models.ImageField(
                        blank=True,
                        help_text="First story grid image on About page",
                        null=True,
                        upload_to="site/about/",
                    ),
                ),
                (
                    "about_story_image_2",
                    models.ImageField(
                        blank=True,
                        help_text="Second story grid image on About page",
                        null=True,
                        upload_to="site/about/",
                    ),
                ),
                (
                    "emailjs_service_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., service_xxxxxxx",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emailjs_template_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g., template_xxxxxxx",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emailjs_public_key",
                    models.CharField(
                        blank=True,
                        help_text="e.g., your_public_key",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emailjs_private_key",
                    models.CharField(
                        blank=True,
                        help_text="Optional, for backend/server usage",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("rating", models.IntegerField(default=5)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/profiles/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrustFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        default="CheckCircle2",
                        help_text="Lucide react icon name",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Trust & Intro Features",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        default="ShieldCheck",
                        help_text="Lucide react icon name",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Why Choose Us Items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AdminUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Module permission dictionary e.g. {'projects': {'view': True, 'edit': False}}",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "author",
                    models.CharField(default="Paramarsh Construction", max_length=255),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.blogcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.faqcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageAdvantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advantages",
                        to="core.package",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PackageFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="core.package",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PackageMaterialSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.TextField()),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("spec", models.TextField(blank=True, null=True)),
                ("why", models.TextField(blank=True, null=True)),
                ("upgrade", models.TextField(blank=True, null=True)),
                ("warranty", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.packagematerialcategory",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_specs",
                        to="core.package",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("built_area", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "floors_count",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "material_grade",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seismic_protection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "architect_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("client_requirements", models.TextField(blank=True, null=True)),
                (
                    "completion_year",
                    models.CharField(
                        blank=True, help_text="e.g. 2024", max_length=50, null=True
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 18 Months",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ₹5 Cr - ₹7 Cr",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("challenges", models.TextField(blank=True, null=True)),
                ("solutions", models.TextField(blank=True, null=True)),
                (
                    "eco_features",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Rainwater Harvesting, Solar Ready",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "scope_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated scope tags, e.g., Civil, Plumbing, Electrical",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.projectcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Before", "Before"),
                            ("Planning", "Planning"),
                            ("Design", "Design"),
                            ("Structure", "Structure"),
                            ("Finished", "Finished"),
                            ("After", "After"),
                        ],
                        default="Finished",
                        max_length=50,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide react icon name, e.g., Building2",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of features as JSON array (used as Key Deliverables in side box)",
                    ),
                ),
                (
                    "estimated_timeline",
                    models.CharField(
                        blank=True,
                        help_text="E.g., '3-6 Months' or 'Contact us' for side box timeline",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'Premium Quality' used in detailed page hero banner",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="services/details/"
                    ),
                ),
                (
                    "scope_text",
                    models.TextField(
                        blank=True,
                        help_text="Detailed text under Scope & Specifications",
                        null=True,
                    ),
                ),
                (
                    "benefits",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of detailed engineering benefits",
                    ),
                ),
                (
                    "workflow_steps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of workflow milestones",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="URL for the staging video", null=True
                    ),
                ),
                (
                    "included_features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of included deliverables",
                    ),
                ),
                (
                    "excluded_features",
                    models.JSONField(
                        blank=True, default=list, help_text="List of excluded items"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.servicecategory",
                    ),
                ),
            ],
        ),
    ]
