# Generated by Django 6.0.7 on 2026-07-16 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagematerialspec",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="packagematerialspec",
            name="spec",
        ),
        migrations.RemoveField(
            model_name="packagematerialspec",
            name="upgrade",
        ),
        migrations.RemoveField(
            model_name="packagematerialspec",
            name="warranty",
        ),
        migrations.RemoveField(
            model_name="packagematerialspec",
            name="why",
        ),
    ]
