# Generated by Django 5.2.16 on 2026-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cta_btn_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_btn_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
