# Generated by Django 6.0.7 on 2026-07-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_packagematerialspec_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagematerialspec",
            name="brand",
            field=models.TextField(),
        ),
    ]
