# Generated by Django 6.0.4 on 2026-07-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_packagematerialspec_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="architect_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="built_area",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="client_requirements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="floors_count",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="material_grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="seismic_protection",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
