# Generated by Django 6.0.4 on 2026-07-17 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_project_architect_name_project_built_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("Planning", "Planning"),
                            ("Design", "Design"),
                            ("Structure", "Structure"),
                            ("Finished", "Finished"),
                        ],
                        default="Finished",
                        max_length=50,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
