# Generated by Django 6.0.4 on 2026-07-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_blogcategory_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="benefits",
            field=models.JSONField(
                blank=True, default=list, help_text="List of engineering benefits"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="detail_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/details/"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="scope_text",
            field=models.TextField(
                blank=True, help_text="Text under Scope & Specifications", null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="E.g., 'Premium Quality'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="video_url",
            field=models.URLField(
                blank=True, help_text="URL for the staging video", null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="workflow_steps",
            field=models.JSONField(
                blank=True, default=list, help_text="List of workflow milestones"
            ),
        ),
    ]
