# Generated by Django 6.0.4 on 2026-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_service_benefits_service_detail_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageSection",
        ),
    ]
