# Generated by Django 6.0.4 on 2026-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_pagesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="hero_headline",
            field=models.TextField(
                blank=True,
                help_text="e.g., Your Dream <br/> Our Build <br/> Complete Site Solutions Under One Roof!",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_poster_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the poster image while video loads",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_video_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the background video for the homepage hero",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
