# Generated by Django 6.0.4 on 2026-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_sitesettings_hero_headline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="hero_video",
            field=models.URLField(
                blank=True,
                help_text="Optional URL to a background video (e.g. mp4). Overrides hero_image if provided.",
                max_length=500,
                null=True,
            ),
        ),
    ]
