# Generated by Django 6.0.4 on 2026-07-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_pagecontent_hero_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="MegaMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'home', 'about', 'services'",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MegaMenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_title", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="core.megamenu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mega Menu Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MegaMenuFeatured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="megamenu/"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional fallback image URL (e.g. Unsplash)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.CharField(help_text="e.g., '/projects'", max_length=255),
                ),
                ("link_text", models.CharField(default="Explore", max_length=100)),
                (
                    "menu",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured",
                        to="core.megamenu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MegaMenuLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("path", models.CharField(help_text="e.g., '/about'", max_length=255)),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Lucide-react icon name, e.g., 'ShieldCheck'",
                        max_length=100,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.megamenucategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
