# Generated by Django 6.0.4 on 2026-07-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_megamenu_megamenucategory_megamenufeatured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagecontent",
            name="hero_video",
            field=models.FileField(
                blank=True,
                help_text="Upload a background video (e.g. mp4). Overrides hero_image if provided.",
                null=True,
                upload_to="pages/videos/",
            ),
        ),
    ]
