# Generated by Django 6.0.4 on 2026-07-21 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_alter_pagecontent_hero_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CompanyStat",
        ),
        migrations.DeleteModel(
            name="Milestone",
        ),
        migrations.DeleteModel(
            name="ProcessStep",
        ),
        migrations.DeleteModel(
            name="TrustPartner",
        ),
    ]
