# Generated by Django 6.0.4 on 2026-07-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_delete_companystat_delete_milestone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="project_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
