# Generated by Django 6.0.4 on 2026-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_testimonial_location_testimonial_project_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="emailjs_private_key",
            field=models.CharField(
                blank=True,
                help_text="Optional, for backend/server usage",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="emailjs_public_key",
            field=models.CharField(
                blank=True, help_text="e.g., your_public_key", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="emailjs_service_id",
            field=models.CharField(
                blank=True, help_text="e.g., service_xxxxxxx", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="emailjs_template_id",
            field=models.CharField(
                blank=True,
                help_text="e.g., template_xxxxxxx",
                max_length=255,
                null=True,
            ),
        ),
    ]
