# Generated by Django 6.0.4 on 2026-07-22 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_sitesettings_emailjs_private_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="megamenucategory",
            name="menu",
        ),
        migrations.RemoveField(
            model_name="megamenulink",
            name="category",
        ),
        migrations.DeleteModel(
            name="MegaMenuFeatured",
        ),
        migrations.DeleteModel(
            name="MegaMenu",
        ),
        migrations.DeleteModel(
            name="MegaMenuCategory",
        ),
        migrations.DeleteModel(
            name="MegaMenuLink",
        ),
    ]
