# Generated by Django 6.0.7 on 2026-07-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_megamenucategory_menu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationsGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="operations_gallery/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Operations Gallery",
                "ordering": ["order"],
            },
        ),
    ]
