# Generated by Django 6.0.7 on 2026-07-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_operationsgallery"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperationsGallery",
        ),
        migrations.AddField(
            model_name="testimonial",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="testimonials/profiles/"
            ),
        ),
    ]
