# Generated by Django 6.0.7 on 2026-07-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_delete_operationsgallery_testimonial_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload a video to show instead of the side image.",
                null=True,
                upload_to="testimonials/videos/",
            ),
        ),
    ]
