# Generated by Django 6.0.7 on 2026-07-24 03:23

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_testimonial_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload a video to show instead of the side image.",
                null=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="testimonials/videos/",
            ),
        ),
    ]
