# Generated by Django 6.0.7 on 2026-07-24 03:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_testimonial_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="video",
        ),
    ]
