# Generated by Django 6.0.7 on 2026-07-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_galleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="estimated_timeline",
            field=models.CharField(
                blank=True,
                help_text="E.g., '3-6 Months' or 'Contact us' for side box timeline",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="benefits",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detailed engineering benefits",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="features",
            field=models.JSONField(
                default=list,
                help_text="List of features as JSON array (used as Key Deliverables in side box)",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="scope_text",
            field=models.TextField(
                blank=True,
                help_text="Detailed text under Scope & Specifications",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="E.g., 'Premium Quality' used in detailed page hero banner",
                max_length=255,
                null=True,
            ),
        ),
    ]
