# Generated by Django 6.0.7 on 2026-07-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_service_estimated_timeline_alter_service_benefits_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_range",
            field=models.CharField(
                blank=True, help_text="e.g. ₹5 Cr - ₹7 Cr", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="challenges",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="completion_year",
            field=models.CharField(
                blank=True, help_text="e.g. 2024", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="duration",
            field=models.CharField(
                blank=True, help_text="e.g. 18 Months", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="solutions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
