# Generated by Django 6.0.7 on 2026-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_project_budget_range_project_challenges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_testimonial",
            field=models.TextField(
                blank=True,
                help_text="Quote from the client for this specific project",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="eco_features",
            field=models.CharField(
                blank=True,
                help_text="e.g., Rainwater Harvesting, Solar Ready",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="scope_tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated scope tags, e.g., Civil, Plumbing, Electrical",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="excluded_features",
            field=models.JSONField(
                blank=True, default=list, help_text="List of excluded items"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="included_features",
            field=models.JSONField(
                blank=True, default=list, help_text="List of included deliverables"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="starting_price",
            field=models.CharField(
                blank=True,
                help_text="e.g., Starting at ₹1500/sq.ft",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("Before", "Before"),
                    ("Planning", "Planning"),
                    ("Design", "Design"),
                    ("Structure", "Structure"),
                    ("Finished", "Finished"),
                    ("After", "After"),
                ],
                default="Finished",
                max_length=50,
            ),
        ),
    ]
