# Generated by Django 6.0.7 on 2026-07-24 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_project_client_testimonial_project_eco_features_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client_testimonial",
        ),
        migrations.RemoveField(
            model_name="service",
            name="starting_price",
        ),
    ]
