# Generated by Django 6.0.7 on 2026-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_project_client_testimonial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagematerialspec",
            name="grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="packagematerialspec",
            name="spec",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagematerialspec",
            name="upgrade",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="packagematerialspec",
            name="warranty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="packagematerialspec",
            name="why",
            field=models.TextField(blank=True, null=True),
        ),
    ]
