# Generated by Django 6.0.7 on 2026-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_packagematerialspec_grade_packagematerialspec_spec_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
