# Generated by Django 6.0.7 on 2026-07-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_blogpost_slug_project_slug_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="JourneyMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="journey/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Company Journey / Timeline",
                "ordering": ["order"],
            },
        ),
    ]
