# Generated by Django 6.0.7 on 2026-07-25 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_journeymilestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculatorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_rate",
                    models.IntegerField(
                        default=1800, help_text="Rate per sq.ft for Essential"
                    ),
                ),
                (
                    "premium_rate",
                    models.IntegerField(
                        default=2200, help_text="Rate per sq.ft for Premium"
                    ),
                ),
                (
                    "luxury_rate",
                    models.IntegerField(
                        default=2800, help_text="Rate per sq.ft for Luxury"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(help_text="e.g. 10+", max_length=50)),
                (
                    "label",
                    models.CharField(help_text="e.g. Years Experience", max_length=100),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="service",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="service",
            name="excluded_features",
        ),
        migrations.RemoveField(
            model_name="service",
            name="features",
        ),
        migrations.RemoveField(
            model_name="service",
            name="included_features",
        ),
        migrations.RemoveField(
            model_name="service",
            name="workflow_steps",
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="cta_button_text",
            field=models.CharField(
                blank=True,
                default="Book a Free Consultation",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="cta_heading",
            field=models.CharField(
                blank=True,
                help_text="Let's Build Your Legacy Together",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="cta_subheading",
            field=models.TextField(
                blank=True, help_text="Contact us for a free site visit...", null=True
            ),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="story_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pagecontent",
            name="story_title",
            field=models.CharField(
                blank=True,
                help_text="Used for About page story section",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="business_hours",
            field=models.TextField(
                blank=True,
                help_text="Mon - Sat: 9:00 AM - 6:00 PM<br/>Sun: Closed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="copyright_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_tagline",
            field=models.TextField(
                blank=True,
                help_text="Your One-Point Solution for All Construction Challenges",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="page",
            field=models.CharField(
                help_text="Page slug (e.g. 'home', 'about', 'service-architectural-design')",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PageStoryChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_checklists",
                        to="core.pagecontent",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon_name", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_benefits",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceExcludedFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_excluded_features",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_features",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceIncludedFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_included_features",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceWorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_workflow_steps",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
