# Generated by Django 6.0.7 on 2026-07-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_calculatorsettings_companystat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceincludedfeature",
            old_name="text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="serviceincludedfeature",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serviceincludedfeature",
            name="icon_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="ServiceSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_specializations",
                        to="core.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
