# Generated by Django 6.0.7 on 2026-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_rename_text_serviceincludedfeature_title_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CalculatorSettings",
        ),
        migrations.DeleteModel(
            name="CompanyStat",
        ),
        migrations.RemoveField(
            model_name="servicebenefit",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceexcludedfeature",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicefeature",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceincludedfeature",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicespecialization",
            name="service",
        ),
        migrations.RemoveField(
            model_name="serviceworkflowstep",
            name="service",
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="cta_button_text",
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="cta_heading",
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="cta_subheading",
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="story_description",
        ),
        migrations.RemoveField(
            model_name="pagecontent",
            name="story_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="business_hours",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="copyright_text",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="footer_tagline",
        ),
        migrations.AddField(
            model_name="service",
            name="benefits",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detailed engineering benefits",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="excluded_features",
            field=models.JSONField(
                blank=True, default=list, help_text="List of excluded items"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="features",
            field=models.JSONField(
                default=list,
                help_text="List of features as JSON array (used as Key Deliverables in side box)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="included_features",
            field=models.JSONField(
                blank=True, default=list, help_text="List of included deliverables"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="workflow_steps",
            field=models.JSONField(
                blank=True, default=list, help_text="List of workflow milestones"
            ),
        ),
        migrations.AlterField(
            model_name="pagecontent",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home"),
                    ("about", "About"),
                    ("services", "Services"),
                    ("packages", "Packages"),
                    ("projects", "Projects"),
                    ("process", "Process"),
                    ("contact", "Contact"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="PageStoryChecklist",
        ),
        migrations.DeleteModel(
            name="ServiceBenefit",
        ),
        migrations.DeleteModel(
            name="ServiceExcludedFeature",
        ),
        migrations.DeleteModel(
            name="ServiceFeature",
        ),
        migrations.DeleteModel(
            name="ServiceIncludedFeature",
        ),
        migrations.DeleteModel(
            name="ServiceSpecialization",
        ),
        migrations.DeleteModel(
            name="ServiceWorkflowStep",
        ),
    ]
