# Generated by Django 6.0.7 on 2026-07-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_adminuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(default='01', help_text='e.g. 01, 02, 03', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='FileText', help_text='Lucide react icon name', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Process Steps / How It Works',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrustFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='CheckCircle2', help_text='Lucide react icon name', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Trust & Intro Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='ShieldCheck', help_text='Lucide react icon name', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us Items',
                'ordering': ['order'],
            },
        ),
    ]
