# Generated by Django 6.0.7 on 2026-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_processstep_trustfeature_whychooseusitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional custom image for this process step', null=True, upload_to='process/'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional video URL for this step', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image_1',
            field=models.ImageField(blank=True, help_text='First story grid image on About page', null=True, upload_to='site/about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image_2',
            field=models.ImageField(blank=True, help_text='Second story grid image on About page', null=True, upload_to='site/about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_primary_btn_text',
            field=models.CharField(blank=True, default='Free Consultation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_secondary_btn_text',
            field=models.CharField(blank=True, default='View Projects', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_pill_1',
            field=models.CharField(blank=True, default='10+ Live Projects', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_stat_pill_2',
            field=models.CharField(blank=True, default='₹1600/sq.ft Starting Price', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtext',
            field=models.TextField(blank=True, help_text='Subheading paragraph under hero title', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_section_poster_image',
            field=models.ImageField(blank=True, help_text='Poster image for How It Works process section', null=True, upload_to='site/process/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_section_video_url',
            field=models.URLField(blank=True, help_text='Video URL for How It Works process section', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_section_image',
            field=models.ImageField(blank=True, help_text='Showcase image for Trust & Intro section', null=True, upload_to='site/trust/'),
        ),
    ]
